// 作品数据（唯一数据源）：首页与第二页、详情页共用，只改这里即可
// 可选字段：
//   img:"images/<id>/cover.jpg"                    → 第二页网格缩略图 + 详情页大图（填了就用真图，不填则显示灰阶色块）
//   logo:"images/<id>/logo.png"                   → 首页品牌墙显示真实 logo 图（填了就用图，不填则显示客户名字标）
//   gallery:["images/<id>/01.jpg","images/<id>/02.jpg", ...]   → 详情页"项目图集"，支持任意数量，双列排布
//   gallery:[{src:"images/<id>/03.jpg",full:true}, ...]        → 标 full:true 的那张占满整行（满宽大图），适合海报/长图；不标则双列
//   图片放在 images/<id>/ 文件夹下，文件名与上面路径对应即可
const works = [
  {id:"aurora",  t:"灼禺·炭火串烧",  cat:"brand", client:"灼禺",  role:"品牌 / VI",   year:"2025",
    img:"images/aurora/cover.jpg", gallery:["images/aurora/01.png","images/aurora/02.png","images/aurora/03.png","images/aurora/04.png","images/aurora/06.png","images/aurora/07.png","images/aurora/08.png"],
    desc:"为炭火串烧品牌「灼禺」打造全套品牌识别。以炭火的温度与夜市烟火气为灵感，建立从 Logo、色彩到应用物料的视觉系统，让街边烧烤也拥有鲜明的记忆点与品质感。"},
  {id:"lumen",   t:"瑕烤·旋转自助烤肉", cat:"brand", client:"瑕烤",        role:"品牌 / VI",   year:"2024", img:"images/lumen/cover.jpg", gallery:["images/lumen/未标题-1-01.png","images/lumen/未标题-1-02.png","images/lumen/未标题-1-03.png","images/lumen/未标题-1-04.png","images/lumen/未标题-1-05.png","images/lumen/未标题-1-06.png","images/lumen/未标题-1-07.png","images/lumen/未标题-1-09.png","images/lumen/未标题-1-10.png"], desc:"围绕「旋转自助」的用餐节奏，为瑕烤设计轻松热烈的视觉语言。高饱和暖色与食欲感图形结合，强化自助烤肉的丰盛与畅快体验。"},
  {id:"city",    t:"STAY LAZY披萨",   cat:"brand", client:"STAY LAZY",     role:"品牌 / VI",  year:"2024", img:"images/city/cover.jpg", gallery:["images/city/未标题-1-01.png","images/city/未标题-1-02.png","images/city/未标题-1-03.png","images/city/未标题-1-04.png","images/city/未标题-1-05.png","images/city/未标题-1-06.png","images/city/未标题-1-07.png","images/city/未标题-1-08.png","images/city/未标题-1-10.png"], desc:"为披萨品牌 STAY LAZY 注入慵懒自在的品牌态度。以松弛的手写感字体与插画，传递慢下来、吃块披萨的生活主张。"},
  {id:"bloom",   t:"悦乐柠·手打柠檬茶", cat:"brand", client:"悦乐柠",   role:"品牌 / VI",  year:"2023", img:"images/bloom/cover.jpg", gallery:["images/bloom/1-01.png","images/bloom/1-02.png","images/bloom/1-03.png","images/bloom/1-04.png","images/bloom/1-05.png","images/bloom/1-06.png","images/bloom/1-07.png"], desc:"为手打柠檬茶品牌「悦乐柠」塑造清新治愈的视觉形象。以柠檬的黄绿与气泡质感传达手打的新鲜感，让产品在茶饮货架上一眼可辨。"},
  {id:"terra",   t:"焙焙很忙·鲜烤面包", cat:"brand", client:"焙焙很忙", role:"品牌 / VI",     year:"2025", img:"images/terra/cover.jpg", gallery:["images/terra/1-01.png","images/terra/1-02.png","images/terra/1-03.png","images/terra/1-04.png","images/terra/1-05.png","images/terra/1-06.png","images/terra/1-07.png","images/terra/1-08.png","images/terra/1-09.png","images/terra/1-11.png"], desc:"为现烤面包品牌「焙焙很忙」构建温暖日常的视觉系统。以麦色与手作质感传递新鲜出炉的香气感，强化社区烘焙店的亲切与信赖。"},
  {id:"street",  t:"POTOTO·薯条",     cat:"brand", client:"POTOTO",     role:"品牌 / VI",         year:"2023", img:"images/street/cover.jpg", gallery:["images/street/1-01.png","images/street/1-02.png","images/street/1-03.png","images/street/1-04.png","images/street/1-05.png","images/street/1-06.png","images/street/1-08.png","images/street/1-09.png","images/street/1-10.png"], desc:"为薯条品牌 POTOTO 设计年轻街头的视觉语言。以明快色彩与几何图形制造零食的趣味与活力，建立轻松解馋的品牌识别。"},
  {id:"nimbus",  t:"ICD·手工酸奶", cat:"brand", client:"ICD",     role:"品牌 / VI",     year:"2024", img:"images/nimbus/cover.jpg", gallery:["images/nimbus/1-01.png","images/nimbus/1-02.png","images/nimbus/1-03.png","images/nimbus/1-05.png","images/nimbus/1-06.png","images/nimbus/1-07.png","images/nimbus/1-08.png"], desc:"为手工酸奶品牌 ICD 建立纯净克制的视觉系统。以柔和乳白与细腻质感传达手工发酵的温度，突出天然与健康的品牌主张。"},
  {id:"pulse",   t:"玲珑小馆",   cat:"brand", client:"玲珑小馆",role:"品牌 / VI",      year:"2025", img:"images/pulse/cover.jpg", gallery:["images/pulse/1-01.png","images/pulse/1-02.png","images/pulse/1-03.png","images/pulse/1-04.png","images/pulse/1-05.png","images/pulse/1-07.png","images/pulse/1-08.png","images/pulse/1-09.png","images/pulse/1-10.png"], desc:"家常中国味，以传统纹样与现代排版结合，呈现温暖、亲切的中式小馆品牌形象。"},
  {id:"drift",   t:"憨三宝·鲜货火锅",   cat:"brand", client:"憨三宝",    role:"品牌 / VI",     year:"2024", img:"images/drift/cover.jpg", gallery:["images/drift/1-02.png","images/drift/1-03.png","images/drift/1-04.png","images/drift/1-05.png","images/drift/1-07.png","images/drift/1-08.png","images/drift/1-10.png","images/drift/1-11.png"], desc:"鲜货火锅品牌，以市井烟火与复古视觉碰撞，传递食材新鲜、氛围热辣的火锅体验。"},
  {id:"work10",  t:"东门王老二",          cat:"brand", client:"东门王老二",           role:"品牌 / VI",            year:"2024", img:"images/work10/cover.jpg", gallery:["images/work10/1-01.png","images/work10/1-02.png","images/work10/1-03.png","images/work10/1-04.png","images/work10/1-05.png","images/work10/1-06.png","images/work10/1-07.png","images/work10/1-09.png","images/work10/1-10.png","images/work10/1-11.png"], desc:"家常红烧菜系品牌，以浓厚的烟火气与质朴的视觉语言，传递地道老味道与人间温情。"},
  {id:"work11",  t:"KING HEYBAO·鑫喜堡",          cat:"brand", client:"鑫喜堡",           role:"品牌 / VI",            year:"2024", img:"images/work11/cover.jpg", gallery:["images/work11/1-01.png","images/work11/1-03.png","images/work11/1-04.png","images/work11/1-05.png"], desc:"美式汉堡快餐品牌，以高饱和红色与食欲感摄影强化冲击力，打造年轻、热烈的用餐体验。"},
  {id:"work12",  t:"斯坦叔叔·炸鸡",          cat:"brand",  client:"斯坦叔叔",           role:"品牌 / VI",            year:"2024", img:"images/work12/cover.jpg", gallery:["images/work12/1-02.png","images/work12/1-03.png","images/work12/1-04.png","images/work12/1-05.png","images/work12/1-06.png"], desc:"美式炸鸡品牌，以金黄酥脆的产品视觉与活泼图形语言，塑造轻松、解馋的快餐形象。"},
  {id:"work13",  t:"谢小宝·鸡爪",          cat:"brand",  client:"谢小宝",           role:"品牌 / VI",            year:"2024", img:"images/work13/cover.jpg", gallery:["images/work13/2b6279e5be80ea8a62758e6a17d73d3.jpg","images/work13/05d7d9be1a5893327b1eab89368436b.jpg","images/work13/850c4da8960810ef96ff7cfbc0e734b.jpg","images/work13/7001a6ed1e1f385adc472512e2e5c0b.jpg","images/work13/aa2cd52ea42957ca9ef059904dc28b5.png","images/work13/d580cdf54f08e95fb9a8f76c31fd4b9.jpg"], desc:"无骨鸡爪小吃品牌，以潮流图形与鲜明色彩打造年轻化、有记忆点的街头美食形象。"},
  {id:"work14",  t:"港叔·茶餐厅",          cat:"brand", client:"港叔",           role:"品牌 / VI",            year:"2024", img:"images/work14/cover.jpg", gallery:["images/work14/1-02.png","images/work14/1-03.png","images/work14/1-04.png","images/work14/1-05.png","images/work14/1_画板 1.png"], desc:"港式茶餐厅品牌，以经典红绿撞色与港风字体重现街头茶记情怀，营造复古又时髦的用餐氛围。"},
  {id:"work15",  t:"嗷椒·成都菜",          cat:"brand", client:"嗷椒",           role:"品牌 / VI",            year:"2024", img:"images/work15/cover.jpg", gallery:["images/work15/1-02.png","images/work15/1-03.png","images/work15/1-05.png","images/work15/1-06.png","images/work15/1-07.png","images/work15/1_画板 1.png"], desc:"成都菜品牌，以热辣红与浓墨黑构建视觉张力，将巴蜀烟火与当代设计语言融合，传递正宗川味魅力。"},
  {id:"work16",  t:"JOYO·中欧",          cat:"brand",  client:"JOYO",           role:"品牌 / VI",            year:"2024", img:"images/work16/cover.jpg", gallery:["images/work16/1_画板 1 副本 2.png","images/work16/1_画板 1 副本 4.png","images/work16/1_画板 1 副本 5.png","images/work16/1_画板 1 副本 6.png","images/work16/1_画板 1 副本 7.png","images/work16/1_画板 1 副本 8.png","images/work16/1_画板 1 副本 9.png","images/work16/1_画板 1 副本 10.png"], desc:"中欧跨境品牌，以极简几何线条构建国际化标识，在东西方视觉语境之间建立清晰、现代的品牌识别。"},
  {id:"poster1", t:"光",                 cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster1/cover.jpg", gallery:[], desc:"以光与暗的对抗为母题，通过几何分割与颗粒渐变，探索文字在极简空间中的呼吸与张力。"},
  {id:"poster2", t:"展",                 cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster2/cover.jpg", gallery:[], desc:"展览主题海报，用高饱和色块与信息堆叠制造视觉节奏，传递当代艺术节的躁动感与开放性。"},
  {id:"poster3", t:"威廉",               cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster3/cover.jpg", gallery:[], desc:"向荷兰设计师威廉·桑德伯格致敬的版式海报，以红蓝撞色与大胆字号再现现代主义精神。"},
  {id:"poster4", t:"走神",               cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster4/cover.jpg", gallery:[], desc:"当代艺术展览海报，用黑白对比与动态模糊表现「走神」的瞬间，在秩序与失控之间寻找平衡。"},
  {id:"poster5", t:"气候",               cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster5/cover.jpg", gallery:[], desc:"摄影展主题海报，以冷静的黑白色调与留白处理，让影像本身成为视觉中心与情绪入口。"},
  {id:"poster6", t:"悟",                 cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster6/cover.jpg", gallery:[], desc:"以《兰亭集序》为灵感的字体实验海报，将传统书法笔画解构重组，呈现东方美学的当代表达。"},
  {id:"poster7", t:"小满",               cat:"poster", client:"ONE WAVE LAB",  role:"海报设计",           year:"2024", img:"images/poster7/cover.jpg", gallery:[], desc:"二十四节气之小满，以新中式视觉语言呈现麦穗初盈、江河渐满的诗意，传统节气与当代图形交织。"},
  {id:"pack1",   t:"猫粮",               cat:"pack",   client:"喵贝语",        role:"包装设计",           year:"2024", img:"images/pack1/cover.jpg",   gallery:["images/pack1/01.jpg","images/pack1/02.jpg"], desc:"无谷猫粮包装设计，以古典花卉与猫咪插画构建精致、天然的宠物食品形象，兼顾货架识别与品质感传达。"},
  {id:"pack2",   t:"嗨吃丸",             cat:"pack",   client:"嗨吃丸",        role:"包装设计",           year:"2024", img:"images/pack2/cover.jpg",   gallery:[], desc:"潮酷风格的功能糖果包装，以高饱和粉色、闪电符号与夸张红唇图形，传递年轻、高能、无惧享乐的品牌态度。"},
  {id:"pack3",   t:"阻Ka",               cat:"pack",   client:"菓而纤",        role:"包装设计",           year:"2024", img:"images/pack3/cover.jpg",   gallery:["images/pack3/01.jpg","images/pack3/02.jpg"], desc:"膳食纤维果冻包装，以修长人物插画与紫黄撞色，塑造轻盈、时尚、女性化的健康零食形象。"},
  {id:"pack4",   t:"类人胶原蛋白肽",     cat:"pack",   client:"麦心诺",        role:"包装设计",           year:"2024", img:"images/pack4/cover.jpg",   gallery:[], desc:"胶原蛋白肽饮品包装，以粉紫渐变与几何光影营造轻盈、现代的美容健康氛围，强化功能感与年轻化表达。"},
  {id:"pack5",   t:"礼盒",               cat:"pack",   client:"南京博物院",    role:"包装设计",           year:"2024", img:"images/pack5/cover.jpg",   gallery:["images/pack5/01.jpg","images/pack5/02.jpg"], desc:"虎年主题礼盒包装，以传统民俗虎图腾与撞色几何拼接，营造浓烈的新年节庆氛围与文化底蕴。"},
  {id:"pack6",   t:"pluto礼盒",          cat:"pack",   client:"PLUTO",         role:"包装设计",           year:"2024", img:"images/pack6/cover.jpg",   gallery:["images/pack6/01.jpg","images/pack6/02.jpg"], desc:"PLUTO 五周年礼盒包装，以纯黑底色搭配烫金 Logo 与插画酒标，呈现低调、克制又不失玩味的限定礼盒气质。"},
  {id:"type1",   t:"字体设计 · 拼贴实验",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type1/cover.png",   gallery:[], desc:"多组字体海报的拼贴展示，用高饱和撞色、几何构成与中西文字混排，呈现字体实验的多元视觉张力。"},
  {id:"type2",   t:"字体设计 · 黑体图形化",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type2/cover.png",   gallery:[], desc:"黑体字的图形化探索，通过拉伸、错位与正负形处理，让现代字体呈现出强烈的节奏感与海报感。"},
  {id:"type3",   t:"携风揽月",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type3/cover.png",   gallery:[], desc:"以宋体为基础的中文字标设计，笔画轻盈上扬，辅以月牙与云纹意象，传递出诗意、浪漫的品牌气质。"},
  {id:"type4",   t:"大牌精英",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type4/cover.png",   gallery:[], desc:"毛笔书法风格字体实验，以飞白与狂放的笔触演绎'一起吃鸡'主题，兼具江湖气与商业海报感染力。"},
  {id:"type5",   t:"字体设计 · 宋体重构",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type5/cover.png",   gallery:[], desc:"宋体字的现代重构，保留横细竖粗的骨架，局部几何化与装饰线处理，探索传统字体的当代审美。"},
  {id:"type6",   t:"类人胶原蛋白肽",     cat:"type",   client:"麦心诺",        role:"字体设计",           year:"2024", img:"images/type6/cover.png",   gallery:[], desc:"为健康饮品定制的科技感字体设计，圆点与断笔的处理让字形既有生物科技属性，又不失亲和力。"},
  {id:"type7",   t:"新速度 新未来",     cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type7/cover.png",   gallery:[], desc:"像素与模块化的字体设计，以几何块面拼合出稳定有力的字形，传递速度、科技与前行的视觉信号。"},
  {id:"type8",   t:"字体设计 · 草书转译",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type8/cover.png",   gallery:[], desc:"草书风格的现代转译，笔画连绵、收放自如，在黑底白字中释放东方书写的流动性与情绪张力。"},
  {id:"type9",   t:"字体设计 · 行书韵律",           cat:"type",   client:"ONE WAVE LAB",  role:"字体设计",           year:"2024", img:"images/type9/cover.png",   gallery:[], desc:"行书韵律的字体实验，强调笔势的连贯与留白节奏，在传统书法与现代排版之间寻找平衡点。"},
];
const catName = {brand:"品牌", pack:"包装", type:"字体", poster:"海报"};
function getWork(id){ return works.find(w=>w.id===id); }
function getNeighbors(id){
  const i = works.findIndex(w=>w.id===id);
  if(i<0) return {prev:null,next:null};
  return {prev:works[(i-1+works.length)%works.length], next:works[(i+1)%works.length]};
}
